### ISSUE TITLE
Silent Failure

### ISSUE THREAD

**Issue by awm33** [jamesward/salesforce-webhook-creator#1]
Hi,

If I authenticate, then fill out the form, and hit "Create Webhook"; the button grays out / disables for a moment, then nothing happens.

If I refresh, no webhook is displayed and if I create/mutate the sobject, nothing happens on the echo.

Name: CreateUpdateLead
SObject: Lead
Events: after insert and after update
URL: https://echo-webhook.herokuapp.com/e4ffaded-acf6-4242-9264-a496cbeccd5e

Any ideas?

**Comment by awm33** [comment]
Trace from the deployment logs:

Code Coverage Failure
Your organization's code coverage is 69%. You need at least 75% coverage to complete this deployment.
Long-Running Tests 
The following tests have long execution times. To improve each test's performance, be sure to follow Apex and SOQL best practices. To learn more, see Performance Tuning Resources for Long-Running Tests
AggregateFunctionHelper_TEST.DMLRecordLimit 2 min 11 sec
Apex Test Failures

Class Name
Method Name
Error Message
PS_Batch_TEST   sum2NoFilter1Filter System.JSONException: No such column 'UserRecordAccessId' on sobject of type rh2__Date_Sync__c 
Stack Trace: (System Code)
PS_Package_Handler_Behaviour    shouldScheduleDailyEmailNotification    System.AssertException: Assertion Failed: Expected: 100, Actual: 0 
Stack Trace: (rh2)
PS_Package_Handler_TEST newInstall  System.AssertException: Assertion Failed 
Stack Trace: (rh2)
PS_RealTime_Rollup_Behaviour    shouldProperlyHandleForeignKeyFilterFields  System.DmlException: Update failed. First exception on row 0 with id 003E0000013zMaQIAU; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, rh2.PS_Contact_Describe_Async: execution of AfterUpdate caused by: System.JSONException: No such column 'UserRecordAccessId' on sobject of type rh2__Date_Sync__c (System Code) : [] 
Stack Trace: (rh2)
PS_Resource_Manager_Behaviour   shouldBundleAsyncRollupsBasedOnSelectedScalingFactor    System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, rh2.PS_Task: execution of AfterInsert caused by: System.JSONException: No such column 'UserRecordAccessId' on sobject of type rh2__Date_Sync__c (System Code) : [] 
Stack Trace: (rh2)
PS_Resource_Manager_Behaviour   shouldRemoveBatchJobsIfTooMany  System.AsyncException: The Apex job named "Rollup Helper Exception Monitor" is already scheduled for execution. 
Stack Trace: (rh2)
PS_Resource_Manager_Behaviour   shouldRescheduleIfInactiveAgent System.AsyncException: The Apex job named "Rollup Helper Exception Monitor" is already scheduled for execution. 
Stack Trace: (rh2)
PS_Resource_Manager_TEST    exceedMaxScheduledJobs  System.AssertException: Assertion Failed: Expected: 101, Actual: 104 
Stack Trace: (rh2)
PS_Trigger1_TEST    limitOnConcatenate  System.AssertException: Assertion Failed: Expected: Test9, Actual: Contact.Description DID NOT WORK 
Stack Trace: (rh2)
PS_Trigger1_TEST    maxCustomSort   System.AssertException: Assertion Failed: Expected: 0, Actual: Contact.Description DID NOT WORK 
Stack Trace: (rh2)
CtrlFirstTimeSyncofAccountsAndZendeskOrg    testBatch1  System.QueryException: List has no rows for assignment to SObject 
Stack Trace: (Zendesk)
CtrlSyncZendeskOrgsandUsers TestCtrlSyncZendeskOrgsandUsers System.LimitException: Zendesk:Too many query rows: 50001 
Stack Trace: (Zendesk)
TestZendeskOrgTriggeronAccounts testmethod2 System.AssertException: Assertion Failed: Expected: null, Actual: 22597836 
Stack Trace: (Zendesk)
TestZendeskOrgTriggeronAccounts testmethod1 System.AssertException: Assertion Failed: Expected: null, Actual: 22597836 
Stack Trace: (Zendesk)
TestZendeskOrgTriggeronContactsLeads    testmethodforcontacts2  System.AssertException: Assertion Failed: Expected: null, Actual: 121212 
Stack Trace: (Zendesk)

**Comment by jamesward** [comment]
It looks like your org has some under-tested code in it.  I think I might be able to make an option that forces deployment in this scenario.  But at the minimum I need to report this error to the UI.

Thanks for reporting this!

**Comment by awm33** [comment]
@jamesward Thanks for getting back to me

We actually do not have any code of our own running. This is our first attempt at anything Apex related, everything else is rest API.

We do have some integrations though, Zen Desk and Pardot. Could they be running code? I saw Zen Desk in the exception output

**Comment by jamesward** [comment]
Those AppExchange packages can have code in them.  So yeah I think the Zen Desk package lacks sufficient code coverage.

**Comment by jamesward** [comment]
I've switched the code to a different way of doing deployment which should fix this.  Let me know if you encounter any issues.
