### ISSUE TITLE
Angular ng-repeat duplicate issue for SObjects

### ISSUE THREAD

**Issue by sterlingwes** [jamesward/salesforce-webhook-creator#10]
Seems the drop-down listing for available Salesforce Objects included duplicates in my test, which resulted in the following error:

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: sobject in sobjects, Duplicate key: string:Lease
http://errors.angularjs.org/1.2.17/ngRepeat/dupes?p0=sobject%20in%20sobjects&p1=string%3ALease
```

Looks like a great resource though, have you come across this issue?

**Comment by sterlingwes** [comment]
Happy to contribute a fix if you can provide a Readme that details how to setup, run the app & run tests.

**Comment by jamesward** [comment]
This fix should be deployed.  I switched from using the `label` to using the `name` which is better anyhow since the API name isn't always the `label` but just happened to be in my tests.
