### ISSUE TITLE
Oops, an error occured

### ISSUE THREAD

**Issue by aeldaly** [jamesward/salesforce-webhook-creator#12]
This exception has been logged with id 6nmngkpo4. I used this utility about a week ago with no issues on the sandbox account, now I'm getting the error above.

**Comment by aeldaly** [comment]
Remote Address:54.243.114.196:443
Request URL:https://salesforce-webhook-creator.herokuapp.com/webhooks
Request Method:POST
Status Code:500 Internal Server Error
Response Headers
view source
Connection:keep-alive
Content-Length:1941
Content-Type:text/html; charset=utf-8
Date:Tue, 13 Oct 2015 21:18:40 GMT
Server:Cowboy
Via:1.1 vegur
Request Headers
view source
Accept:application/json, text/plain, _/_
Accept-Encoding:gzip, deflate
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Length:122
Content-Type:application/json;charset=UTF-8
Cookie:PLAY_SESSION=6b427c4555fb7909ecc47c29e4a25bd7a931d655-oauthAccessToken=00D1a000000Ifxi%21AR0AQNfbxeNmWWaARjz8t4s5a9cPFTHoANTOdeHO3YOiaPfXOHgHtKXTykLjYTjdg1G_cQCusGEgrx929gqhS4eRO3YSm2eO&env=prod
Host:salesforce-webhook-creator.herokuapp.com
Origin:https://salesforce-webhook-creator.herokuapp.com
Pragma:no-cache
Referer:https://salesforce-webhook-creator.herokuapp.com/app
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
Request Payload
view source
{name: "aa", sobject: "Account", events: ["after undelete"],…}
events: ["after undelete"]
name: "aa"
sobject: "Account"
url: "https://salesforce-webhook-creator.herokuapp.com/app"

**Comment by jamesward** [comment]
Thanks for reporting this.  The error I'm seeing is:

```
Can not create Apex Class on an active organization.
```

So I think you'll have to create the Webhook on a sandbox and them migrate it to your production org.

Does that help?

**Comment by aeldaly** [comment]
Yes. Thanks!
