### ISSUE TITLE
Tests fail on deployment to production

### ISSUE THREAD

**Issue by shankie-codes** [jamesward/salesforce-webhook-creator#13]
Hey @jamesward 

I've created a webhook on my sandbox org and it all works great. I've moved the classes to prod using change sets (successful), but when I do to deploy the changes, it runs the unit tests which result in a failure

```
System.NullPointerException: Attempt to de-reference a null object 
Stack Trace: Class.Hijinx_Logs_to_StagingWebhookTriggerTest.testTrigger: line 81, column 1
```

The code at line 81 is:

`System.assertEquals(200, response.getStatusCode());`

Any idea what might be going on? I've tried running the tests in the sandbox and they pass, where they fail in prod.

**Comment by shankie-codes** [comment]
Ok, I think I've got past that issue – it's because I had only deployed the Apex Class, and not the trigger as well. Now, when I deploy both the class and the trigger, I get a new error in the trigger:

`Variable does not exist: Webhook`

Thoughts?

**Comment by jamesward** [comment]
You also need to deploy the Webhook class and it's test.

**Comment by shankie-codes** [comment]
Oops! I guess that bit should have been obvious. I've deployed the class, but I can't find the test to deploy, and as a result, I'm only getting 65% test code coverage. I can't find any reference to tests for the webhook class in the source – what should I be looking for in my sandbox to deploy a test for the webhook class?

**Comment by jamesward** [comment]
Ah, yeah it looks like the only test is for the trigger which should provide coverage for the Webhook class.  Are you seeing lower test coverage when you include the 3 classes vs when you don't?

**Comment by shankie-codes** [comment]
Hmm. It worked when I deployed all three classes at the same time! i.e.:

![image](https://cloud.githubusercontent.com/assets/2608862/18482753/61c1f614-79d9-11e6-8e70-a4268c6917ea.png)

Pretty confusing as the Webhook class on its own has code coverage of 94% when in the sandbox environment. Perhaps it's because those other classes are already there and providing tests.

Anyways, hope this helps anyone else who was in my situation!

**Comment by jamesward** [comment]
Glad you got it figured out!
