### ISSUE TITLE
API 37: Double `@` gives error in editor

### ISSUE THREAD

**Issue by cworsley4** [jamesward/salesforce-webhook-creator#15]
I was altering some of the code generated by your template and I received an error that there was an unexpected `@` character. Here is the line... https://github.com/jamesward/salesforce-webhook-creator/blob/master/app/apextemplates/classes/Webhook.scala.txt#L20

Removing one of the two `@` chars fixed the error. Perhaps consider removing from the template as well or version for APIs if that was deprecated.

**Comment by jamesward** [comment]
Were you using the template via the webhook creator app?  Those files run through the Twirl template engine and `@@` escapes a `@` char.  So for the app the double `@@` is necessary.  But if you are using the template outside of the app, then yeah, you will need to remove an `@` manually.  Does that help?

**Comment by cworsley4** [comment]
Ah, sorry for the false alarm @jamesward I was using your code outside of the creator, sorry for the confusion.
