### ISSUE TITLE
Apex Test Failures

### ISSUE THREAD

**Issue by leevigraham** [jamesward/salesforce-webhook-creator#16]
Hi,

I'm trying to create a Outgoing Change Set and when I run the Apex tests for the webhook class I get the following:

System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out Stack Trace: Class.Webhook.callout: line 31, column 1

<img width="971" alt="screen shot 2016-12-06 at 2 03 48 am" src="https://cloud.githubusercontent.com/assets/25124/20889747/43af08cc-bb58-11e6-8db2-92f94c3b651a.png">

Any ideas?

**Comment by jamesward** [comment]
Sorry about the problem.  I tried to reproduce this and couldn't.  What events does your trigger fire on?  Do you have other triggers on Lead?

**Comment by leevigraham** [comment]
Turns out this is an issue with having an existing workflow action. http://salesforce.stackexchange.com/questions/71259/issue-with-email-alerts-and-test-setmock-uncommitted-work-pending
