### ISSUE TITLE
Empty sobjects list

### ISSUE THREAD

**Issue by adelaby** [jamesward/salesforce-webhook-creator#2]
When I login via salesforce-webhook-creator to my salesforce instance the sobjects list is empty.

**Comment by jamesward** [comment]
Can you check your browser JavaScript console and see if there are any errors there?

**Comment by adelaby** [comment]
For some reason I can't reproduce the bug today. Everything is working properly... I'm closing the issue for now, will re-open it if the bug occurs again.

**Comment by jamesward** [comment]
Sounds good.  Thanks for the update.

**Comment by KevinGreene** [comment]
I'm actually experiencing this issue currently.

The specific error message is 

`System.DmlException: Update failed. First exception on row 0 with id 00516000004vpaaAAA; first error: FIELD_INTEGRITY_EXCEPTION, Cannot change profile for current user: [ProfileId] && System.QueryException: List has no rows for assignment to SObject`

The only javascript error is a 500 response to "https://salesforce-webhook-creator.herokuapp.com/webhooks", which only contains the previous error message.

![salesforce_webhook_creator](https://cloud.githubusercontent.com/assets/320528/7357469/fb1a4b6a-ecfc-11e4-9807-037af69d7ce7.png)

Any help would be appreciated.

**Comment by KevinGreene** [comment]
If this is a separate issue, let me know and I'll open it separately

**Comment by jamesward** [comment]
Hmmm...  Not sure what the problem is with this one.  Can you file a new issue for this?  Sorry for the hassle.
