### ISSUE TITLE
Bug in SObjects and Webhooks

### ISSUE THREAD

**Issue by xban1x** [jamesward/salesforce-webhook-creator#25]
Hello,

 I tried to create a webhook today and it has an error that prevents it from working. I have tried circumventing your UI and it still did not work.

Can you please check or point me in the right direction?

Sincerely, xban1x

**Comment by jamesward** [comment]
Could you tell what the error was?  If you open the network inspector and look at the raw response, does that give you a more detailed error?

**Comment by xban1x** [comment]
Actually, today I retried it and now it seems to be working. It was 500 Internal Server Error saying "Ooops something went wrong" or similar. The response was a HMTL Error page.
