### ISSUE TITLE
SObject drop-down is empty

### ISSUE THREAD

**Issue by ByronStone** [jamesward/salesforce-webhook-creator#28]
No dropdown for Objects appears, does that mean my salesforce login does not have the proper permissions?

**Comment by jamesward** [comment]
Thanks for filing. Can you check the browser console and let me know if you see any errors there when the page loads?

**Comment by ByronStone** [comment]
here's what I can see but I don't really know if I'm looking at the right spot in brower console.
![error2](https://user-images.githubusercontent.com/69826395/90455303-1af6f880-e139-11ea-9d1a-ad62fe816cac.png)
![error1](https://user-images.githubusercontent.com/69826395/90455310-1df1e900-e139-11ea-8fb7-d84cb0d7b85b.png)

**Comment by jamesward** [comment]
Ah, you aren't getting into my app.  Maybe something is blocking / messing with your cookies?  I'm using cookies to pass oauth stuff through the oauth flow.

**Comment by jamesward** [comment]
BTW, the error console is one of the tabs in that inspector.

**Comment by ByronStone** [comment]
Thanks James.  What do you suggest?  I did just try from a different computer (on a different network) with a different browser and it still doesn't work which leads me to still believe it has something to do with our salesforce permissions.

**Comment by jamesward** [comment]
Cool. Thanks for ruling that out.  It is weird that the error says something about an expired auth code.

Do you see that error page above when you try to login to the webhook creator app?

**Comment by ByronStone** [comment]
No, I don't see the error page when I login in (only when I look at the browser log).

Maybe it has something to do with this.  I cleared my browser history and cookies and you'll note I receive this secondary security check to verify my identity when logging into Salesforce.   

![Verify_Your_Identity___Salesforce](https://user-images.githubusercontent.com/69826395/90457049-d3bf3680-e13d-11ea-9c46-ffe7c82fe42f.png)

**Comment by ByronStone** [comment]
maybe there's a why to turn that off in Salesforce?

**Comment by ByronStone** [comment]
![Profiles___Salesforce](https://user-images.githubusercontent.com/69826395/90457414-cc4c5d00-e13e-11ea-99ff-3b36df97c776.png)

**Comment by jamesward** [comment]
Two-Factor auth should be fine.  What all happens when you go to: http://salesforce-webhook-creator.herokuapp.com/app

**Comment by ByronStone** [comment]
Still no luck.

The URL it's passing seems to be this (if that helps at all).... 

https://ironcapital.my.salesforce.com/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAXQEESKiME8wMEswMDAwMDA4T0k3AAAA4gHhZv8pSO6_JOSakmO4UQkKmWoQRbgE0TOa4uNsgS-AbUBPu9LplD0WgZPpFKhlCSBFWcij3EgvRPWxnHBgin0XTluG8CkW-mhWE1L8oVezqF8YC6RQNkyT-cho4D6J16CJZNGSlcKy9cTEsudTwVXJNRNxdjGgQUsJtoaDFy95ZVEPxoqdI-7LpbBjtKY3Es4k4vNE3wIBjvD7Fbplhev-U1JpE-khBf88ceC-zg8l05depEOoW2Tc20aq1LDNwvOhKQgo7oOmCLpwEfr-fYBQNJHbBdNvQf4TwN66yOxNLUZ_aroGkOUrVKPS-5ZyKE-5G8NE4w8yrVdA9GQMhAVsr92tUl4nB7rvNrr1n5VmJtpdX1jthbbkrJdHigc3OQ8DlLRdNIl__DhoTxJBzwZ4MEgfbvoFZuoGO4EJP7CCUpFXF4HmJwy-RodIiX1nyTPlp2KAWb4O6i49Eexlhyt1ZPXzLRNVaIRItf8oaP44SNq4huRbiTzmA0PwsQb1fCZMpi4wuXDDKyweeQEKDn1esCBsfGSa797bERShviwpYjHYbFwutb7cgiKS6oQhZPYNKZco8kDV92VjFCsChAgadqf2jYB1F0Wwd0bkAxKBD0zccD8VUgMQGLgZaXBG9tilSQ1hXUzIhkyJHFvp-0WR4X_UeaZHJ122hfrPgzIelB5N_f2f-Q5WY7rpDQzd9g%3D%3D&sdtd=1

**Comment by jamesward** [comment]
So when you go to https://salesforce-webhook-creator.herokuapp.com/app then click on login, it goes to that URL and displays the error image you posted above?

**Comment by ByronStone** [comment]
Hi James, no I'm not really seeing that page load... here's a screen movie of what it looks like on my end and where I got that URL.

https://dataminegroup.com.au/wp-content/uploads/2020/08/webhook-screen.mov

**Comment by ByronStone** [comment]
Sorry to pester you James but do you have any more thoughts or ideas on how we can get this working, or are you at the point of giving up?   Please let me know your thoughts and I really appreciate your help!!

**Comment by jamesward** [comment]
Thanks for the movie!  That definitely helps me figure out where to look next.  I think you are right about permissions.

**Comment by jamesward** [comment]
@ByronStone Does your user have the `System Administrator` profile?

**Comment by jamesward** [comment]
@ByronStone I've added some debugging.  Can you try again: https://salesforce-webhook-creator.herokuapp.com/app?debug=true
Let me know when you do that and I'll check the logs.

**Comment by ByronStone** [comment]
Hi James - I just tried it now.  Let me know how you go.

**Comment by ByronStone** [comment]
And yes, we have System Administrator profile

**Comment by jamesward** [comment]
Can you try https://salesforce-webhook-creator.herokuapp.com/app?debug=true again?  It looks like it didn't log what I needed.

**Comment by ByronStone** [comment]
Hi James, just ran it again.

**Comment by jamesward** [comment]
Ah geeze. Apparently my there is a bug in my debugging logic.  I need you to:
1. Go to https://salesforce-webhook-creator.herokuapp.com/
1. Login
1. Then go to: https://salesforce-webhook-creator.herokuapp.com/app?debug=true

(Background, on login the cookies get reset which is causing the `debug=true` to be lost after you login.  So you have to be logged in when you go to that URL for it to log the info I need.)

Sorry for the hassle!

**Comment by ByronStone** [comment]
No worries at all.  Done.  Have just done steps 1, 2, 3.

**Comment by jamesward** [comment]
Thanks! Got it that time.  Continuing my investigation.  For some background... I tried to reproduce the issue several ways and couldn't.  This made me think that it had something to do with the "describle global" api call.  Now I have that response for you so I can see what went wrong.

**Comment by ByronStone** [comment]
Thanks James... I really appreciate you spending the time following this up.

**Comment by jamesward** [comment]
So the issue is that none of your sobjects have the `triggerable` flag.  I'm not sure what causes that...  Perhaps you need to use a sandbox org, add the webhook, then deploy it to prod?
