### ISSUE TITLE
System.AsyncException: Future method cannot be called from a future or batch method: Webhook.callout(String, String)

### ISSUE THREAD

**Issue by soldmtrieu** [jamesward/salesforce-webhook-creator#35]
Thanks for creating this webhook.

I've installed it and it seems to be mostly working, except sometimes I run into this error:

> NodeWebhookOpportunitiesTrigger: execution of AfterUpdate
> 
> caused by: System.AsyncException: Future method cannot be called from a future or batch method: Webhook.callout(String, String)

It sounds like Salesforce doesn't allow a future method to be called from another future method or a batch job.

I'm going to try implementing this "defensive apex" pattern, but wondering if there's a better way.

```
public void defensiveFutureCall{
    if(System.isFuture() || System.isBatch()){
        regularSyncCall();
    } else {
        if(Limits.getFutureCalls() < Limits.getLimitFutureCalls()){
            doFutureCall();
        } else {
            // Do some explicit notification so that you know your @future call was denied
        }
    }
}

@future
public void doFutureCall(){
    regularSyncCall();
}

public void regularSyncCall(){
    // Put the code, that you'd otherwise put in your @future method, in here
}
```

https://salesforce.stackexchange.com/a/102200/121206

**Comment by jamesward** [comment]
That makes sense to me.  Want to send a PR with that update?

**Comment by soldmtrieu** [comment]
Thanks for the quick response!

It doesn't look like sync callouts are allowed from triggers either.

I got this error after trying the defensive pattern in Webhook.

> execution of AfterUpdate caused by: System.CalloutException: Callout from triggers are currently not supported. Class.Webhook.syncCallout:

I'm going to try adding flag check to apex trigger instead.

Will close out issue once this is deployed and working in my production environment (doing some final testing/deployment).

```java
trigger AccountsTrigger on Account (after insert, after update) {
  if (System.IsBatch() == false && System.isFuture() == false) {
    IntegrationSettings__c integrationSettings = IntegrationSettings__c.getOrgDefaults();
    String url = integrationSettings.API_Url__c + '/salesforce/v2/webhooks/accounts';
    String content = Webhook.jsonContent(Trigger.new, Trigger.old);
    Webhook.callout(url, content);
  }
}
```

**Comment by soldmtrieu** [comment]
Update, adding the conditional statement in trigger seems to have solved the problem.

Closing this one out.
