### ISSUE TITLE
Unable to Proceed once login 

### ISSUE THREAD

**Issue by nishanpatel** [jamesward/salesforce-webhook-creator#4]
Hi James,

I have cloned git hub project and make necessary configuration. After that when I ran application I am able to login into app, but after login I can't get page any other page. Even if I manually making other URL I can't get that page.

Please find below image every time I was getting after salesforce login.

![capture](https://cloud.githubusercontent.com/assets/175758/6371727/6fdd642c-bd24-11e4-853b-19c30e0e33d6.PNG)

**Comment by jamesward** [comment]
Are you getting any errors in the sbt run output or in the Chrome developer console?

**Comment by nishanpatel** [comment]
I don't see any error on sbt run output as well as in Chrome developer console. I don't understand even if I change url manually it was redirecting me on same below url.

http://localhost:9000/?code=aPrxaSyVmC8fBbeyfOWqvYFzlJLGLTh2Gxd79LZaqiOf2bs1MFwlSmnLL.Sfj8t9rbMzdLjGqA%3D%3D

**Comment by jamesward** [comment]
You should either set some breakpoints or add some printlns in the Scala code to see what is going wrong with the OAuth process.

**Comment by nishanpatel** [comment]
Ok, Thanks James let me investigate more further and will come back to you.

**Comment by nishanpatel** [comment]
Hi James,

Looks like typo in your route file at line no.20. By mistake committed vassets instead of assets.

**Comment by jamesward** [comment]
`vassets` is correct.  It is the _Versioned Assets_.

**Comment by nishanpatel** [comment]
Hi James,

I found the issue. I have set wrong call back url in my salesforce remote app configuration.

**Comment by jamesward** [comment]
Glad you figured it out!
