### ISSUE TITLE
Creating webhooks fails - List has no rows for Assignment sObject

### ISSUE THREAD

**Issue by KevinGreene** [jamesward/salesforce-webhook-creator#6]
The specific error message is 

`System.DmlException: Update failed. First exception on row 0 with id 00516000004vpaaAAA; first error: FIELD_INTEGRITY_EXCEPTION, Cannot change profile for current user: [ProfileId] && System.QueryException: List has no rows for assignment to SObject`

The only javascript error is a 500 response to "https://salesforce-webhook-creator.herokuapp.com/webhooks", which only contains the previous error message.

![salesforce_webhook_creator](https://cloud.githubusercontent.com/assets/320528/7357469/fb1a4b6a-ecfc-11e4-9807-037af69d7ce7.png)

Any help would be appreciated.

**Comment by jamesward** [comment]
Hmm... That is a strange one.  Can you see if there is any more info the the `Deployment Status` part of `Setup`?  I can't tell if this is a test failure or something else.

Sorry for the hassle.

**Comment by KevinGreene** [comment]
Ah, thanks for pointing me in the right direction. In addition to the error I posted before, it's notifying me that the organization has dipped below 75% code coverage. Given that this worked before, I'm inclined to think that someone added untested code, and will look into that.

For now, I think that's the root cause of this issue and I'll close it.

**Comment by KevinGreene** [comment]
I looked into it a bit more, and it is definitely an issue with tests that are unrelated to the webhook creator. Thanks again for the help in debugging.

**Comment by jamesward** [comment]
Thanks for diving into this.  I've tried to make the deployment not run the tests but it looks like that isn't happening.  I need to dive further into this.

**Comment by jamesward** [comment]
It looks like there is no way to not run all of the tests in a production org:
https://www.salesforce.com/us/developer/docs/apexcode/Content/apex_deploying_ant_deploy.htm
