### ISSUE TITLE
Object validation error while trying to create a webhook

### ISSUE THREAD

**Issue by ilyakatz** [jamesward/salesforce-webhook-creator#7]
Hi there, when I try to create a webook, I get the following error

"System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Contact Type is required: [] && System.DmlException:"

Does it try to validate all objects before creating a webhook?

**Comment by jamesward** [comment]
Thanks for filing an issue.  Unfortunately deployment of a Webhook requires that all of the tests in an org succeed.  See #6.  So the easiest way to fix this is to get all of your tests passing.

Maybe I need a way to allow users to create the Webhooks manually.  Until then, you could create the objects manually.  You can see all of the templates for the classes in: https://github.com/jamesward/salesforce-webhook-creator/tree/master/app/templates

**Comment by ilyakatz** [comment]
@jamesward maybe silly questions, but what tests are you talking about? does that happen on Salesforce? So are webhook not a standard feature of SF and does your app deploy something?

**Comment by jamesward** [comment]
Yeah, the Webhook creator deploys some Apex code in your org.  You can see more details about the deployment error in the `Deployment Status` part of `Setup`.

**Comment by jamesward** [comment]
I've switched to code over to use the REST API which I think should fix this and all similar errors.  It will be deployed in about 10 minutes and will need some testing though.
