### ISSUE TITLE
README.md file

### ISSUE THREAD

**Issue by ffxsam** [jamesward/salesforce-webhook-creator#8]
Just a suggestion: a README would be nice, detailing how to install this and set it up.

**Comment by jamesward** [comment]
Are you looking for usage info or do you want to run this on your own infrastructure?  For usage info, see: http://www.jamesward.com/2014/06/30/create-webhooks-on-salesforce-com

**Comment by rafaeljesus** [comment]
@jamesward It would be awesome to have a README so we can run this on our own infrastructure, any plans for that?

**Comment by jamesward** [comment]
I've added a README with deployment instructions.  Let me know if that is sufficient.

**Comment by rafaeljesus** [comment]
Nice job @jamesward thank a lot for your quick reply
