### ISSUE TITLE
Salesforce Error - Actor Not Found

### ISSUE THREAD

**Issue by dmyers** [jamesward/salesforce-webhook-creator#9]
@jamesward Have you seen this error before?

```
Actor not found for: ActorSelection[Anchor(akka://application/), Path(/user/]
```

**Comment by jamesward** [comment]
I recently added support for long deployments.  I'm guessing that something has gone wrong with that.  I'll investigate.

**Comment by jamesward** [comment]
I've switched the code to a different method of code deployment that should fix this.  Feel free to re-open this if you have any issues.
